# Generated by Django 4.1.5 on 2023-01-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('job_id', models.CharField(blank=True, max_length=150, null=True)),
                ('job_status', models.CharField(blank=True, choices=[('Started', 'Started'), ('Running', 'Running'), ('Finished', 'Finished'), ('Failed', 'Failed'), ('Ready', 'Ready'), ('Pending', 'Pending')], default='Ready', max_length=15, null=True)),
                ('content', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
