# Generated by Django 4.1.5 on 2023-01-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_session_delete_scrapedwebsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='task_status',
            new_name='status',
        ),
    ]
