FROM python:3.10 

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY ./pyproject.toml /pyproject.toml

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install

COPY ./docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh


COPY . .